name: Update Test Branch

on:
  push:
    branches: [main]
    
permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.KRYPTO_BOT_APPID }}
          private-key: ${{ secrets.KRYPTO_BOT_SECRET }}
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"
          git config user.email "<EMAIL>"

      - name: Update Test Branch
        run: |
          git checkout main
          git fetch origin
          git checkout offseason-base
          git pull
          git merge origin/main
          git push origin offseason-base
