name: Statistics Tracker

on:
  push

permissions:
  pages: write
  id-token: write

jobs:

  build:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./stats_tracker
    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Imgkit
        run: |
          pip install imgkit
      - name: Install wkhtmltopdf
        run: |
          sudo apt-get install wkhtmltopdf
      - name: Generate SVG graphic
        id: build
        run: bash ./generate_svg.sh
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: stats_tracker/build/

  main-deploy:
    if: ${{github.ref != 'refs/heads/main'}}
    uses:
      FRC2593/javabot-2025/.github/workflows/statistics.yml@main

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4